### ISSUE TITLE
Where is the library on CRAN?

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [MPIBGC-TEE/SoilR-exp#2]
I could no longer find the library on CRAN and some of the document links are also dead.
Cheers,
Daniel

**Comment by mamueller** [comment]
https://cran.r-project.org/web/packages/SoilR/index.html

**Comment by crlsierra** [comment]
The CRAN server was down during the weekend, but it is running again. You can find the package in the link provided above.

**Comment by Daniel-Trung-Nguyen** [comment]
Thank you! Just out of curiosity, do you guys have a plan to create a similar python library?

**Comment by crlsierra** [comment]
We have three python packages that overlap in most of the functionality with SoilR, but are more general in scope.
[LAPM](https://github.com/MPIBGC-TEE/LAPM) provides functions to analyze compartmental/pool models at equilibrium. [CompartmentalSystems](https://github.com/MPIBGC-TEE/CompartmentalSystems) provides functions to analyze models out of equilibrium. [BGC-MD](https://github.com/MPIBGC-TEE/bgc_md2) is a data base of ecosystem carbon models that can help you decide what type of analysis you can perform. These three packages are not targeted to soil carbon models as in SoilR, but can be used to run and analyze any mass-balanced model.

**Comment by Daniel-Trung-Nguyen** [comment]
@crlsierra Thank you for the answer! I am particularly interested in the implementation of the Century model in soilR. I am not sure how that can be done in Python using those python packages?

**Comment by crlsierra** [comment]
For how to implement models in LAPM or CompartmentalSystems, please check the documentation of those packages.

**Comment by mamueller** [comment]
The century model is already in bgc-md2
as
https://github.com/MPIBGC-TEE/bgc_md2/blob/master/src/bgc_md2/models/Parton1987SoilSciSocAmJ/source.py

What do you want to do with it.
p.s.
If you are at AGU by any chance we can work together on a small example.

Cheers
Markus

**Comment by Daniel-Trung-Nguyen** [comment]
Thanks @mamueller! I'll take a look at this.
I have been using the compiled versions of Century and DayCent for a long time for landscape simulations of soil C stock change, so it will reduce the computational burden to have part of the model implemented in Python.
I am currently developing the DayCent-AU model at the Queensland University of Technology. You can check out some tutorials here: https://www.youtube.com/@daycentmodel9086
Unfortunately, I am not at the AGU this year, but let me know your interests and perhaps we can collaborate in the future.
Best,
Trung
