### ISSUE TITLE
package vignettes

### ISSUE THREAD

**Issue by kendalynnm** [MPIBGC-TEE/SoilR-exp#4]
Hello SoilR team!

I am looking to get started with learning SoilR and noticed that the vignettes were removed due to being out-of-date:
https://github.com/MPIBGC-TEE/SoilR/commit/fa618d016d3897c44ea092b8aa7ebafc54a4c28e

Are there plans to update these in the near future? Or are there any other resources you would recommend for learning the package?

Thanks for your time,
Best wishes,
Kendal

**Comment by crlsierra** [comment]
Hi Kendal,
Great to know you're interested in learning about SoilR.
The best place to get started would be our tutorials available in this page:
[SoilR at MPI-BGC](https://www.bgc-jena.mpg.de/TEE/software/soilr/)
The two published papers are also a good place to learn about the theory behind the package.
You can also write me if you have questions.
Cheers,
Carlos

**Comment by kendalynnm** [comment]
Awesome, the tutorial page looks like a fantastic resource. Thank you very much! I will definitely reach out with questions.
